### ISSUE TITLE
首次测试部署中的一些问题解决

### ISSUE THREAD

**Issue by lzj790911** [Feysh-Group/corax-community#1]
1、环境部署
测试下来最低环境要求  centos7 + jav1.7 + gradle 7.4
2、构建
根目录corax-java-config实际为corax-community
首次执行gradlew build提示不存在，用./gradlew build
失败后再生成gradle-local.properties配置文件,修改引擎的的路径后再执行./gradlew build
3、部署完成运行
在缺少主配置文件的情况下，引擎会帮自动生成，官方执行脚本只需要修改引擎绝对路径就可以。

**Comment by notify-bibi** [comment]
非常感谢大佬提供的宝贵建议，文档已经修改了哈
