### ISSUE TITLE
是否支持自定义sanitizers

### ISSUE THREAD

**Issue by testnet0** [Feysh-Group/corax-community#2]
没有找到文档有相关说明，是需要自己用代码实现吗？

**Comment by notify-bibi** [comment]
支持的，不过文档还没更新，我们会马上更新，实现在这里 [TaintSanitizerPropagate](https://github.com/Feysh-Group/corax-community/blob/main/corax-config-general/src/main/kotlin/com/feysh/corax/config/general/model/processor/Propagate.kt#L74) ,  和 [sanitizerTaintTypesMap](https://github.com/Feysh-Group/corax-community/blob/main/corax-config-general/src/main/kotlin/com/feysh/corax/config/general/model/taint/TaintModelingConfig.kt#L42)
json中添加类似如下 rule 去除 sql 注入的污点: 
```json
  {"signature":"<org.joychou.security.SecurityUtil: java.lang.String sqlFilter(java.lang.String)>","subtypes":true,"to":"Argument[0]","propagate":"sanitizer","from":"sql","provenance":"manual","ext":""},
```
或者全部去除
```json
  {"signature":"<org.joychou.security.SecurityUtil: java.lang.String sqlFilter(java.lang.String)>","subtypes":true,"to":"Argument[0]","propagate":"taint","from":"empty","provenance":"manual","ext":""},
```
