### ISSUE TITLE
No config exists in the local env: CORAX_CONFIG_DEFAULT_DIR

### ISSUE THREAD

**Issue by wuerror** [Feysh-Group/corax-community#3]
不自己编译，使用release版本。
设置CORAX_CONFIG_DEFAULT_DIR=/tools/corax-community/analysis-config/
在第一次分析时，default-config.yml并未如文档所说自动生成

**Comment by notify-bibi** [comment]
麻烦再试试，我这边测试了是正常的
linux:  `export CORAX_CONFIG_DEFAULT_DIR=/tools/corax-community/analysis-config/` 
windows cmd: `set  CORAX_CONFIG_DEFAULT_DIR=set CORAX_CONFIG_DEFAULT_DIR=D:\corax-java-cli-community-2.0-product\analysis-config` 
实在不行可以使用 --config default-config.yml@D:\corax-java-cli-community-2.0-product\analysis-config 达到一样的效果
