### ISSUE TITLE
关于提示设置内存大小的bug

### ISSUE THREAD

**Issue by testnet0** [Feysh-Group/corax-community#6]
![image](https://github.com/Feysh-Group/corax-community/assets/18673513/efa97e70-a5ac-408a-a9d3-cc5c1ddd5ea6)

You can add the following command before run analysis to fully utilize the machine's performance:
	 > export _JAVA_OPTIONS="-Xmx=0.5g"
提示通过这种方式修改内存大小，但是执行命令后会提示错误：
![image](https://github.com/Feysh-Group/corax-community/assets/18673513/224714d8-a904-46c9-b7b7-e88ca1182757)
应该修改为这种方式：
export _JAVA_OPTIONS='"-Xmx8g" "-Xms64m"'

**Comment by notify-bibi** [comment]
感谢您的反馈，这是我们开发的一时疏忽多加了个＝符号，我们下个版本会修复

**Comment by notify-bibi** [comment]
2.6 版本已经 fix
